name: admg
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.28.0
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libcxx=19.1.2
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.11.10
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - pip:
      - ananke-causal==0.1.5
      - autograd==1.7.0
      - ig==0.0.1
      - igraph==0.11.8
      - matplotlib==3.9.2
      - mpmath==1.3.0
      - networkx==3.3
      - numpy
      - pandas==2.2.3
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - sentry-sdk==2.18.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - statsmodels==0.14.4
      - sympy==1.13.3
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - torch==2.4.1
      - tqdm==4.66.5
      - tzdata==2024.2
      - urllib3==2.2.3
      - wandb==0.18.7
prefix: /opt/anaconda3/envs/admg
